aluno-- MySQL Script generated by MySQL Workbench
-- Tue Mar  3 22:42:08 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SistemaEpis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SistemaEpis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaEpis` DEFAULT CHARACTER SET utf8 ;
USE `SistemaEpis` ;

-- -----------------------------------------------------
-- Table `SistemaEpis`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaEpis`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nomeCompleto` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `setor` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  UNIQUE INDEX `idFuncionario_UNIQUE` (`idFuncionario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaEpis`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaEpis`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeCompleto` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `funcao` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaEpis`.`Visitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaEpis`.`Visitante` (
  `idVisitante` INT NOT NULL AUTO_INCREMENT,
  `nomeCompleto` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `empresa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVisitante`),
  UNIQUE INDEX `idVisitante_UNIQUE` (`idVisitante` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaEpis`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaEpis`.`Aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nomeCompleto` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  `turma` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `idAluno_UNIQUE` (`idAluno` ASC) VISIBLE,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaEpis`.`Equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaEpis`.`Equipamento` (
  `idEquipamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `certificadoAprovacao` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `validade` DATE NOT NULL,
  `tamanho` VARCHAR(45) NULL,
  `classificacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEquipamento`),
  UNIQUE INDEX `idEquipamento_UNIQUE` (`idEquipamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaEpis`.`Movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaEpis`.`Movimentacao` (
  `idMovimentacao` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `quantidade` INT NOT NULL,
  `observacao` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Funcionario_idFuncionario` INT NULL,
  `Aluno_idAluno` INT NULL,
  `Visitante_idVisitante` INT NULL,
  `Equipamento_idEquipamento` INT NOT NULL,
  PRIMARY KEY (`idMovimentacao`, `Equipamento_idEquipamento`, `Visitante_idVisitante`, `Aluno_idAluno`, `Funcionario_idFuncionario`, `Usuario_idUsuario`),
  UNIQUE INDEX `idMovimentacao_UNIQUE` (`idMovimentacao` ASC) VISIBLE,
  INDEX `fk_Movimentacao_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Movimentacao_Funcionario1_idx` (`Funcionario_idFuncionario` ASC) VISIBLE,
  INDEX `fk_Movimentacao_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  INDEX `fk_Movimentacao_Visitante1_idx` (`Visitante_idVisitante` ASC) VISIBLE,
  INDEX `fk_Movimentacao_Equipamento1_idx` (`Equipamento_idEquipamento` ASC) VISIBLE,
  CONSTRAINT `fk_Movimentacao_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `SistemaEpis`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimentacao_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `SistemaEpis`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimentacao_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `SistemaEpis`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimentacao_Visitante1`
    FOREIGN KEY (`Visitante_idVisitante`)
    REFERENCES `SistemaEpis`.`Visitante` (`idVisitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimentacao_Equipamento1`
    FOREIGN KEY (`Equipamento_idEquipamento`)
    REFERENCES `SistemaEpis`.`Equipamento` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaEpis`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaEpis`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `quantidadeAtual` INT NOT NULL,
  `estoqueMinimo` INT NOT NULL,
  `Equipamento_idEquipamento` INT NOT NULL,
  UNIQUE INDEX `idEstoque_UNIQUE` (`idEstoque` ASC) VISIBLE,
  PRIMARY KEY (`idEstoque`, `Equipamento_idEquipamento`),
  INDEX `fk_Estoque_Equipamento1_idx` (`Equipamento_idEquipamento` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Equipamento1`
    FOREIGN KEY (`Equipamento_idEquipamento`)
    REFERENCES `SistemaEpis`.`Equipamento` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaEpis`.`Solicitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaEpis`.`Solicitacao` (
  `idSolicitacao` INT NOT NULL,
  `data` DATE NOT NULL,
  `quantidade` INT NOT NULL,
  `justificativa` VARCHAR(100) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `Equipamento_idEquipamento` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idSolicitacao`, `Equipamento_idEquipamento`, `Usuario_idUsuario`),
  UNIQUE INDEX `idSolicitacao_UNIQUE` (`idSolicitacao` ASC) VISIBLE,
  INDEX `fk_Solicitacao_Equipamento1_idx` (`Equipamento_idEquipamento` ASC) VISIBLE,
  INDEX `fk_Solicitacao_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Solicitacao_Equipamento1`
    FOREIGN KEY (`Equipamento_idEquipamento`)
    REFERENCES `SistemaEpis`.`Equipamento` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitacao_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `SistemaEpis`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaEpis`.`Emprestado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaEpis`.`Emprestado` (
  `idEmprestado` INT NOT NULL,
  `Movimentacao_idMovimentacao` INT NOT NULL,
  `Equipamento_idEquipamento` INT NOT NULL,
  UNIQUE INDEX `idEmprestado_UNIQUE` (`idEmprestado` ASC) VISIBLE,
  PRIMARY KEY (`idEmprestado`, `Movimentacao_idMovimentacao`, `Equipamento_idEquipamento`),
  INDEX `fk_Emprestado_Movimentacao1_idx` (`Movimentacao_idMovimentacao` ASC) VISIBLE,
  INDEX `fk_Emprestado_Equipamento1_idx` (`Equipamento_idEquipamento` ASC) VISIBLE,
  CONSTRAINT `fk_Emprestado_Movimentacao1`
    FOREIGN KEY (`Movimentacao_idMovimentacao`)
    REFERENCES `SistemaEpis`.`Movimentacao` (`idMovimentacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Emprestado_Equipamento1`
    FOREIGN KEY (`Equipamento_idEquipamento`)
    REFERENCES `SistemaEpis`.`Equipamento` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
